feature: support 004 accounts
standardnotes/decrypt pull request #2
Opened 2020-10-14 10:53 UTC by baptiste-grob

- The script is now using Typescript + dependencies to ensure compatibility with SNJS and avoiding hard-coding as many scripts as possible
- At build time, the generated script is inlined in the `decrypt.html` file so users still only have to download one file

2020-10-14 14:01 UTC, mobitar requested changes
Two things:

1. Should use storage policy ephemeral as not to persist any data: https://github.com/standardnotes/snjs/blob/004/lib/services/storage_service.ts#L105

2. Should call application.signOut after use to destroy any data that may otherwise have been saved anywhere.

2020-10-14 14:52 UTC, baptiste-grob commented
setPersistencePolicy is only called upon signing in or registering. Is it safe to set it at any time during the app lifecycle?

2020-10-14 17:05 UTC, mobitar commented
Yup should be.

On Wed, Oct 14, 2020 at 9:52 AM Baptiste Grob <notifications@github.com>
wrote:

> setPersistencePolicy is only called upon signing in or registering. Is it
> safe to set it at any time during the app lifecycle?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/standardnotes/decrypt/pull/2#issuecomment-708456116>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZAIFET4HRUAYIURAYXT6TSKW3MJANCNFSM4SQOEJTA>
> .
>

2020-10-16 13:44 UTC, mobitar commented on src/index.ts
> +    localStorage.setItem(
This device interface really should be memory based overall. It's another insurance policy against data persistence. So the keychain should be an in-memory data structure, as well as the payload store. Really we shouldn't see any references of localStorage.

2020-10-19 13:18 UTC, mobitar approved these changes

2020-10-20 09:51 UTC, merged